Add device model name
gojuno/commander pull request #12
Opened 2018-02-01 02:15 UTC by koral--

First step of https://github.com/gojuno/composer/issues/122

2018-02-01 08:03 UTC, artem-zinnatullin requested changes
Looks good but few comments :)

2018-02-01 08:03 UTC, artem-zinnatullin commented on android/src/main/kotlin/com/gojuno/commander/android/Adb.kt
> +fun deviceModel(serial: String): Observable<String> = process(listOf(adb, "-s", serial, "shell", "getprop ro.product.model undefined"))
Let's use Single here, it's not gonna change nor we actually observe it :)

2018-02-01 08:03 UTC, artem-zinnatullin commented on android/src/main/kotlin/com/gojuno/commander/android/Adb.kt
> +            deviceModel(line.substringBefore("\t"))
Hmm, I don't like that we have to do it here, let's move parsing of actual decide model into deviceModel function?

2018-02-01 08:03 UTC, artem-zinnatullin commented on android/src/main/kotlin/com/gojuno/commander/android/Adb.kt
> +fun deviceModel(serial: String): Observable<String> = process(listOf(adb, "-s", serial, "shell", "getprop ro.product.model undefined"))
We also need to test it (parsing, trimming)

2018-02-01 08:03 UTC, artem-zinnatullin commented on android/src/main/kotlin/com/gojuno/commander/android/Adb.kt
> +fun deviceModel(serial: String): Observable<String> = process(listOf(adb, "-s", serial, "shell", "getprop ro.product.model undefined"))
And looks like we can pass AdbDevice as parameter rather than just a string that could allow someone to pass wrong value without realizing it

2018-02-02 09:12 UTC, yunikkk approved these changes

2018-02-02 18:59 UTC, artem-zinnatullin approved these changes

2018-02-02 18:59 UTC, merged

2018-02-02 19:00 UTC, artem-zinnatullin commented
Great, thanks @koral--!